# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Efimerum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Efimerum
pod 'Firebase/Core'

  target 'EfimerumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
