# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Efimerum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Efimerum
  source 'https://github.com/CocoaPods/Specs.git'
  
  pod 'Hero'
  pod 'GreedoLayout'
  # pod 'Koloda', '~> 4.0'
  pod 'pop', '~> 1.0'
  pod 'Firebase/Core'

  target 'EfimerumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
