# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Efimerum' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Efimerum
  source 'https://github.com/CocoaPods/Specs.git'

  pod 'Gloss'
  pod 'Alamofire'
  pod 'Result'	
  pod 'Hero'
  pod 'GreedoLayout'
  pod 'pop', '~> 1.0'
  pod 'PKHUD', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  target 'EfimerumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
